version: '3.8'

services:
  toolbox:
    build: .
    ports:
      - "8080:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    volumes:
      # 挂载运行时目录以持久化缓存和日志
      - ./runtime:/www/toolbox/runtime
    restart: unless-stopped
    
  # 可选：添加 MySQL 数据库服务（如果需要）
  # mysql:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: toolbox
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   restart: unless-stopped

# volumes:
#   mysql_data:
